[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
build = "build.rs"
description = "AWS SDK for Rust - Core"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
keywords = ["AWS", "Amazon"]
license = "MIT"
name = "rusoto_core"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.33.1"
homepage = "https://www.rusoto.org/"

[badges]
travis-ci = { repository = "rusoto/rusoto", branch = "master" }
appveyor = { repository = "rusoto/rusoto", branch = "master" }

[build-dependencies]
rustc_version = "0.2.1"

[dependencies]
futures = "0.1.16"
hmac = "0.5.0"
hyper = "0.12.0"
lazy_static = "1.0"
log = "0.4.1"
md5 = "0.3.6"
base64 = "0.9"
hex = "0.3"
serde = "1.0.2"
sha2 = "0.7.0"
time = "0.1.35"
url = "1.6.0"
tokio = "0.1.7"
tokio-timer = "0.2.1"
xml-rs = "0.7"

[dependencies.hyper-tls]
optional = true
version = "0.2.0"

[dependencies.hyper-rustls]
optional = true
version = "0.14.0"

[dependencies.rusoto_credential]
path = "../credential"
version = "0.12"

[dependencies.clippy]
optional = true
version = "0.0"

[dev-dependencies]
env_logger = "0.5"
rand = "0.4.2"
serde_json = "1.0.1"
serde_test = "1.0.1"

[features]
default = []
nightly-testing = ["clippy", "rusoto_credential/nightly-testing"]
unstable = []

native-tls = ["hyper-tls", "rusoto_credential/native-tls"]
rustls = ["hyper-rustls", "rusoto_credential/rustls"]